// <auto-generated />
using System;
using HoTroKhachHang.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HoTroKhachHang.Data.Migrations
{
    [DbContext(typeof(CSKHContext))]
    [Migration("20210622034930___InitDB__")]
    partial class __InitDB__
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.ChucDanh", b =>
                {
                    b.Property<string>("MaChucDanh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maChucDanh");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenChucDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenChucDanh");

                    b.HasKey("MaChucDanh")
                        .HasName("PK__ChucDanh__2284EAF37681A2D3");

                    b.ToTable("ChucDanh");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.HoiDap", b =>
                {
                    b.Property<string>("MaHoiDap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHoiDap");

                    b.Property<bool>("CongKhai")
                        .HasColumnType("bit")
                        .HasColumnName("congKhai");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maLoai");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maSanPham");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maTrangThai");

                    b.Property<string>("NdHoiDap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ndHoiDap");

                    b.Property<string>("NdHoiDapEdit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ndHoiDapEdit");

                    b.Property<string>("NdTraLoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ndTraLoi");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("date")
                        .HasColumnName("ngayNhan");

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("date")
                        .HasColumnName("ngayXuatBan");

                    b.Property<string>("TraVeDuyet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traVeDuyet");

                    b.Property<string>("TraVeXuatBan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traVeXuatBan");

                    b.HasKey("MaHoiDap")
                        .HasName("PK__HoiDap__A6533CEA5ECAC499");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("HoiDap");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.KeyLicense", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maSanPham");

                    b.Property<int>("GiaHan")
                        .HasColumnType("int")
                        .HasColumnName("giaHan");

                    b.Property<DateTime>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("ngayBD");

                    b.Property<DateTime>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("ngayKT");

                    b.HasKey("MaKhachHang", "MaSanPham")
                        .HasName("PK__KeyLicen__297F048D804237CE");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KeyLicense");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("Anh")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("anh");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chucVu");

                    b.Property<string>("CoQuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("coQuan");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho");

                    b.Property<string>("LinhVuc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("linhVuc");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<DateTime?>("NgayTuyen")
                        .HasColumnType("date")
                        .HasColumnName("ngayTuyen");

                    b.Property<string>("Passwd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passwd");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("trinhDo");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("userName");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__0CCB3D49818C18C3");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.LoaiHoiDap", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maLoai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenLoai");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiHoiD__E5A6B2284A5ED66A");

                    b.ToTable("LoaiHoiDap");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.LoaiTaiLieu", b =>
                {
                    b.Property<string>("MaLoaiTaiLieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maLoaiTaiLieu");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenLoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenLoaiTaiLieu");

                    b.HasKey("MaLoaiTaiLieu")
                        .HasName("PK__LoaiTaiL__52492BD98ABD6B31");

                    b.ToTable("LoaiTaiLieu");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("anh");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ho");

                    b.Property<string>("MaChucDanh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maChucDanh");

                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhongBan");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<DateTime?>("NgayTuyenDung")
                        .HasColumnType("date")
                        .HasColumnName("ngayTuyenDung");

                    b.Property<string>("Passwd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passwd");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trinhDo");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("userName");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__BDDEF20DF3B327EA");

                    b.HasIndex("MaChucDanh");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvHoiDap", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MaHoiDap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maHoiDap");

                    b.Property<DateTime?>("NgayThang")
                        .HasColumnType("date")
                        .HasColumnName("ngayThang");

                    b.Property<string>("NoiDungThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDungThucHien");

                    b.Property<string>("Quyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quyen");

                    b.HasKey("MaNhanVien", "MaHoiDap")
                        .HasName("PK__NV_HoiDa__07BBC1C32854A8A6");

                    b.HasIndex("MaHoiDap");

                    b.ToTable("NV_HoiDap");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvQuyen", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MaQuyen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maQuyen");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaNhanVien", "MaQuyen")
                        .HasName("PK__NV_Quyen__94AEF3D7ACB0C455");

                    b.HasIndex("MaQuyen");

                    b.ToTable("NV_Quyen");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvTaiLieu", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MaTaiLieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maTaiLieu");

                    b.Property<DateTime>("NgayThang")
                        .HasColumnType("date")
                        .HasColumnName("ngayThang");

                    b.Property<string>("NoiDungThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDungThucHien");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quyen");

                    b.HasKey("MaNhanVien", "MaTaiLieu")
                        .HasName("PK__NV_TaiLi__A1CF3F912F332BED");

                    b.HasIndex("MaTaiLieu");

                    b.ToTable("NV_TaiLieu");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maPhongBan");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenPhongBan");

                    b.HasKey("MaPhongBan")
                        .HasName("PK__PhongBan__3A946B0864E6FA53");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.Quyen", b =>
                {
                    b.Property<string>("MaQuyen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maQuyen");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenQuyen");

                    b.HasKey("MaQuyen")
                        .HasName("PK__Quyen__97001DA3580159C9");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maSanPham");

                    b.Property<string>("Anh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("anh");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngayTao");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenSanPham");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__5B439C43B2F7C944");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.TaiLieu", b =>
                {
                    b.Property<string>("MaTaiLieu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maTaiLieu");

                    b.Property<bool>("DownLoad")
                        .HasColumnType("bit")
                        .HasColumnName("downLoad");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("duongDan");

                    b.Property<string>("MaLoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maLoaiTaiLieu");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maSanPham");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maTrangThai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("date")
                        .HasColumnName("ngayDang");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenFile");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenTaiLieu");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tieuDe");

                    b.HasKey("MaTaiLieu")
                        .HasName("PK__TaiLieu__C11CD9C006E2E13D");

                    b.HasIndex("MaLoaiTaiLieu");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.TrangThai", b =>
                {
                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maTrangThai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenTrangThai");

                    b.HasKey("MaTrangThai")
                        .HasName("PK__TrangTha__AD42D179B08221B9");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.HoiDap", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HoiDap__maKhachH__3F466844")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.LoaiHoiDap", "MaLoaiNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__HoiDap__maLoai__403A8C7D")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.SanPham", "MaSanPhamNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__HoiDap__maSanPha__412EB0B6")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK__HoiDap__maTrangT__4222D4EF")
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.KeyLicense", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.KhachHang", "MaKhachHangNavigation")
                        .WithMany("KeyLicenses")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__KeyLicens__maKha__4316F928")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.SanPham", "MaSanPhamNavigation")
                        .WithMany("KeyLicenses")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__KeyLicens__maSan__440B1D61")
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.ChucDanh", "MaChucDanhNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucDanh")
                        .HasConstraintName("FK__NhanVien__maChuc__44FF419A");

                    b.HasOne("HoTroKhachHang.Data.Entities.PhongBan", "MaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK__NhanVien__maPhon__45F365D3");

                    b.Navigation("MaChucDanhNavigation");

                    b.Navigation("MaPhongBanNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvHoiDap", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.HoiDap", "MaHoiDapNavigation")
                        .WithMany("NvHoiDaps")
                        .HasForeignKey("MaHoiDap")
                        .HasConstraintName("FK__NV_HoiDap__maHoi__46E78A0C")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.NhanVien", "MaNhanVienNavigation")
                        .WithMany("NvHoiDaps")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__NV_HoiDap__maNha__47DBAE45")
                        .IsRequired();

                    b.Navigation("MaHoiDapNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvQuyen", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.NhanVien", "MaNhanVienNavigation")
                        .WithMany("NvQuyens")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__NV_Quyen__maNhan__48CFD27E")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.Quyen", "MaQuyenNavigation")
                        .WithMany("NvQuyens")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__NV_Quyen__maQuye__49C3F6B7")
                        .IsRequired();

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NvTaiLieu", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.NhanVien", "MaNhanVienNavigation")
                        .WithMany("NvTaiLieus")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__NV_TaiLie__maNha__4AB81AF0")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.TaiLieu", "MaTaiLieuNavigation")
                        .WithMany("NvTaiLieus")
                        .HasForeignKey("MaTaiLieu")
                        .HasConstraintName("FK__NV_TaiLie__maTai__4BAC3F29")
                        .IsRequired();

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaTaiLieuNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.TaiLieu", b =>
                {
                    b.HasOne("HoTroKhachHang.Data.Entities.LoaiTaiLieu", "MaLoaiTaiLieuNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaLoaiTaiLieu")
                        .HasConstraintName("FK__TaiLieu__maLoaiT__4E88ABD4")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.SanPham", "MaSanPhamNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__TaiLieu__maSanPh__4CA06362")
                        .IsRequired();

                    b.HasOne("HoTroKhachHang.Data.Entities.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK__TaiLieu__maTrang__4D94879B")
                        .IsRequired();

                    b.Navigation("MaLoaiTaiLieuNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.ChucDanh", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.HoiDap", b =>
                {
                    b.Navigation("NvHoiDaps");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.KhachHang", b =>
                {
                    b.Navigation("HoiDaps");

                    b.Navigation("KeyLicenses");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.LoaiHoiDap", b =>
                {
                    b.Navigation("HoiDaps");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.LoaiTaiLieu", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("NvHoiDaps");

                    b.Navigation("NvQuyens");

                    b.Navigation("NvTaiLieus");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.Quyen", b =>
                {
                    b.Navigation("NvQuyens");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.SanPham", b =>
                {
                    b.Navigation("HoiDaps");

                    b.Navigation("KeyLicenses");

                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.TaiLieu", b =>
                {
                    b.Navigation("NvTaiLieus");
                });

            modelBuilder.Entity("HoTroKhachHang.Data.Entities.TrangThai", b =>
                {
                    b.Navigation("HoiDaps");

                    b.Navigation("TaiLieus");
                });
#pragma warning restore 612, 618
        }
    }
}
